### ISSUE TITLE
docker启动命令

### ISSUE THREAD

**Issue by lesterhnu** [baidu/bifromq-docs#3]
不算问题但是强迫症较难受
![image](https://github.com/baidu/bifromq-docs/assets/42615458/9f1495e8-20f9-4cb2-8089-9efd13e8a921)

**Comment by visoar** [comment]
Thank you for your feedback. We will make the necessary changes soon. 
Additionally, you can also submit a PR to help us improve the content.

非常感谢反馈，我们会尽快修正。当然，后续你也可以考虑提交 PR 的方式参与修改。

**Comment by visoar** [comment]
Fix @ https://github.com/baidu/bifromq-docs/commit/0a48840b606bdd666bd7a0d02d32984d5e50788d
