### ISSUE TITLE
[BifroMQ Inside] auth-plugin for bifromq

### ISSUE THREAD

**Issue by Gujiawei-Edinburgh** [baidu/bifromq-docs#5]
Name: gujiawei

Description: auth-plugin for bifromq plugin development

URL: https://github.com/Gujiawei-Edinburgh/bifromq-plugin

Category:such as IoT platforms, Cloud services, plugins or other

Tags:Plugins
---
Some additional information from you.

**Comment by visoar** [comment]
1. Please provide a more detailed description, showcasing the functions and features of this scene.
2. The plugin name should be modified to make it more distinct and less generic. For example, consider using names like bifromq-plugin-`auth` or `ANYNAME addition`.

**Comment by Gujiawei-Edinburgh** [comment]
ok, according to the comments, I rename the module and packages. And also I add some stuff for auth plugin scenario explaination in README.

**Comment by visoar** [comment]
commit @ https://github.com/baidu/bifromq-docs/commit/e65e8a69805d224c0a03ca58ce948d224635229a
